

#ifndef __MYMEMDEV_H
#define __MYMEMDEV_H

#define MYMEMDEV_IOC_MAGIC	'y'
#define MYMEMDEV_IOCRESET	_IO(MYMEMDEV_IOC_MAGIC,   0)
#define MYMEMDEV_IOCSMAXSIZE	_IOW(MYMEMDEV_IOC_MAGIC,  1, unsigned long)
#define MYMEMDEV_IOCGMAXSIZE	_IOR(MYMEMDEV_IOC_MAGIC,  2, unsigned long)
#define MYMEMDEV_IOCTMAXSIZE	_IO(MYMEMDEV_IOC_MAGIC,   3)
#define MYMEMDEV_IOCQMAXSIZE	_IO(MYMEMDEV_IOC_MAGIC,   4)
#define MYMEMDEV_IOCXMAXSIZE	_IOWR(MYMEMDEV_IOC_MAGIC, 5, unsigned long)
#define MYMEMDEV_IOCHMAXSIZE	_IO(MYMEMDEV_IOC_MAGIC,   6)
#define MYMEMDEV_IOC_MAXNR	6

#endif
